# Devnet0 is a tiny devnet. Only a single validator and two anvils.
# This is aimed at local dev environments.

network = "devnet"
anvil_chains = ["mock_op", "mock_arb"]

explorer = true

[node.validator01]
